version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tasksdb

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    depends_on:
      - database
    ports:
      - "4000:4000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=tasksdb

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
      - server
